language: csharp

matrix:
  fast_finish: true

before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq

install:
  - sudo apt-get install -yq emacs24 emacs24-el emacs24-common-non-dfsg

script:
  - make test-all

