git remote add ace-jump-mode         https://github.com/winterTTr/ace-jump-mode.git
git remote add actionscript-mode     https://github.com/austinhaas/actionscript-mode.git
git remote add auto-complete         https://github.com/auto-complete/auto-complete.git
git remote add auto-complete-clang   https://github.com/brianjcj/auto-complete-clang.git
git remote add fuzzy-el              https://github.com/auto-complete/fuzzy-el.git
git remote add popup-el              https://github.com/auto-complete/popup-el.git
git remote add codesearch            https://github.com/abingham/codesearch.el
git remote add dash.el               https://github.com/magnars/dash.el.git
git remote add evil                  git://gitorious.org/evil/evil.git
git remote add expand-region.el      https://github.com/magnars/expand-region.el.git
git remote add emacs-ctable          https://github.com/kiwanami/emacs-ctable.git
git remote add emacs-deferred        https://github.com/kiwanami/emacs-deferred.git
git remote add emacs-epc             https://github.com/kiwanami/emacs-epc.git
git remote add emacs-jedi            https://github.com/tkf/emacs-jedi.git
git remote add git-modes             https://github.com/magit/git-modes.git
git remote add magit                 https://github.com/magit/magit.git
git remote add markdown-mode         git://jblevins.org/git/markdown-mode.git
git remote add multiple-cursors.el   https://github.com/magnars/multiple-cursors.el.git
git remote add nyan-mode             https://github.com/TeMPOraL/nyan-mode.git
git remote add org-mode              git://orgmode.org/org-mode.git
git remote add smex                  https://github.com/nonsequitur/smex.git
git remote add wrap-region           https://github.com/rejeep/wrap-region.git
git remote add yasnippet             https://github.com/capitaomorte/yasnippet.git
